spring:
  application:
    name: SearchVirtual
  datasource:
    url: jdbc:mysql://localhost:3306/search?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  threads:
    virtual:
      enabled: true

server:
  tomcat:
    protocol: HTTP/1.1
    executor:
      virtual-threads: true
